# If true, all resources defined by this chart will be enabled.
enabled: true
# A list of CustomResourceDefinition names to be protected from deletion.
resources:
  - alertmanagerconfigs.monitoring.coreos.com
  - alertmanagers.monitoring.coreos.com
  - podmonitors.monitoring.coreos.com
  - probes.monitoring.coreos.com
  - prometheusagents.monitoring.coreos.com
  - prometheuses.monitoring.coreos.com
  - prometheusrules.monitoring.coreos.com
  - scrapeconfigs.monitoring.coreos.com
  - servicemonitors.monitoring.coreos.com
  - thanosrulers.monitoring.coreos.com
